# Generated by Django 5.2.4 on 2025-07-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_remove_message_recipients_remove_message_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecipient',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sms.message'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sms.recipient'),
        ),
    ]
