version: '3.3'

services:
  app:
    container_name: sms-gateway
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: pavelcode5426-sms-gateway:latest
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: sms_gateway
      DB_USER: root
      DB_PASSWORD: root_password
    networks:
      - listmonk_listmonk
      - sms-gateway-net

  mysql:
    container_name: sms-gateway-db
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sms_gateway
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - sms-gateway-net

networks:
  sms-gateway-net:
    name: sms-gateway-net
    driver: bridge
  listmonk_listmonk:
    external: true